FROM node:22-alpine AS base

WORKDIR /app

COPY package*.json ./
RUN npm install

FROM base AS dev

EXPOSE 3000

CMD ["npm", "run", "dev"]

FROM base AS builder

COPY . .
RUN npm run build

FROM node:22-alpine AS production

WORKDIR /app

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]
